package com.shop.glass.shop.dao;

import com.shop.glass.shop.domain.GlassShopUser;
import com.shop.glass.shop.domain.GlassShopUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import javax.annotation.Resource;

public interface GlassShopUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    long countByExample(GlassShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int deleteByExample(GlassShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int insert(GlassShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int insertSelective(GlassShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    GlassShopUser selectOneByExample(GlassShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    GlassShopUser selectOneByExampleSelective(@Param("example") GlassShopUserExample example, @Param("selective") GlassShopUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    List<GlassShopUser> selectByExampleSelective(@Param("example") GlassShopUserExample example, @Param("selective") GlassShopUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    List<GlassShopUser> selectByExample(GlassShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    GlassShopUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GlassShopUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    GlassShopUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    GlassShopUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GlassShopUser record, @Param("example") GlassShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GlassShopUser record, @Param("example") GlassShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GlassShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GlassShopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GlassShopUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_shop_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}